services:
  backend:
    volumes:
      - .:/app

    build:
      context: .
    environment:
      - PYTHONUNBUFFERED=1
    container_name: django_backend
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: mysql:8.0
    container_name: django_mysql
    restart: always
    environment:
      MYSQL_DATABASE: recipehub
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
