# Generated by Django 5.2 on 2025-04-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_meat_eater',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_vegan',
        ),
        migrations.AddField(
            model_name='customuser',
            name='diet_preference',
            field=models.CharField(blank=True, choices=[('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('meat', 'Meat Eater'), ('gluten_free', 'Gluten-Free'), ('keto', 'Keto')], max_length=50, null=True),
        ),
    ]
